name: shoe_buy
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # utility packages
  http: ^1.4.0
  intl: ^0.18.1
  logger: ^2.5.0
  url_launcher: ^6.3.1
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.0.0

  # icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  #state management 
  get: ^4.7.2
  get_storage: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Project assets
  assets:
  - assets/images/
  #- assets/logos/
  - assets/fonts/
  #- assets/images/on_boarding_images/



  # Custom fonts
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-MediumItalic.ttf
        weight: 500
        style: italic
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        weight: 600
        style: italic
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-BoldItalic.ttf
        weight: 700
        style: italic